"""fourth migration

Revision ID: 598f365f15fe
Revises: f14d71ad486c
Create Date: 2018-02-10 11:40:57.107821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598f365f15fe'
down_revision = 'f14d71ad486c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'category')
    # ### end Alembic commands ###
