"""third  migration

Revision ID: f14d71ad486c
Revises: 32dc15c35a43
Create Date: 2018-02-10 08:35:04.549257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14d71ad486c'
down_revision = '32dc15c35a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('blogpic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogposts', 'blogpics', ['blogpic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogposts', type_='foreignkey')
    op.drop_column('blogposts', 'blogpic_id')
    # ### end Alembic commands ###
